name: CI Pipeline (Test API)

# Robot ini bekerja setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode
    - uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. Install (FORCE INSTALL)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest httpx fastapi uvicorn requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Cek Library (Debug)
    - name: Check installed packages
      run: |
        python -m pip list

    # 5. Test
    - name: Test with pytest
      run: |
        python -m pytest