name: CI Pipeline (Test API)

# Robot ini bekerja setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Jalanin di komputer virtual Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kodingan kita dari repo
    - uses: actions/checkout@v3

    # 2. Siapkan Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. Install Library (FastAPI, Pytest, dll)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Jalanin Test 
    - name: Test with pytest
      run: |
        python -m pytest